services:
  modulacion_amplitud:
    build:
      context: ./BackEnd/ModulacionAmplitud
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  modulacion_digital:
    build:
      context: ./BackEnd/ModulacionDigital
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

  modulacion_pulsos:
    build:
      context: ./BackEnd/ModulacionPulsos
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - app-network

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge